### ISSUE TITLE
Wrong parsing for "Stufe"

### ISSUE THREAD

**Issue by LucStr** [bula21/mova21-orca#103]
When I open up [this page](https://orca.mova21.ch/units/940?locale=en) I am shown the following information:
![image](https://user-images.githubusercontent.com/25279790/133314721-d4ca945d-6203-40a7-b302-32ec9c75bd0e.png)
I'd assume this is wrong. I am unsure if this only affects this specific camp or if every camp is affected by it.

**Comment by jimmylevell** [comment]
In the meanwhile this issue has been addressed.
