### ISSUE TITLE
Expected Number of participants, wrong locale if english is selected 

### ISSUE THREAD

**Issue by LucStr** [bula21/mova21-orca#104]
This is located on the unit overview (/units/id). The wrong Gender is within the locale:
![image](https://user-images.githubusercontent.com/25279790/133315121-4622babb-1e51-414a-b701-92033c2ca6be.png)

German in comparison:

![image](https://user-images.githubusercontent.com/25279790/133315187-14084955-eb81-4ecd-be12-9d52ac1d9fbf.png)

**Comment by jimmylevell** [comment]
In the meanwhile this issue has been addressed.
