### ISSUE TITLE
Unit starts_at und ends_at werden nicht validiert

### ISSUE THREAD

**Issue by diegosteiner** [bula21/mova21-orca#96]
Achtung: allenfalls gibt es schon falsche Units, die müssten dann noch angepasst werden

**Comment by Jonas-Marty** [comment]
sind damit die Lagerstart und -end Daten gemeint? Da ist unsere Abteilung und andere aus SZ bereits reingefallen, da sie davon ausgegangen sind, dass sie angaben aus Orca stimmen. Sie haben die Lagerdaten nie mit den An-/Abreise daten auf mova.ch abgeglichen (gab diesbezüglich keine explizite TN-Information durch TN-Admin).

**Comment by jimmylevell** [comment]
Closed due to inactivity
